name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ou 'master' selon le nom de votre branche principale

jobs:
  # 1. COMPILATION ET DÉPLOIEMENT WEB (Ton code d'origine)
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🏗️ Build Web
        run: flutter build web --release --base-href "/Perfos/"

      - name: 🚀 Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web # Le dossier généré par Flutter
          branch: gh-pages  # La branche de destination

  # 2. COMPILATION AUTOMATIQUE WINDOWS
  build-windows:
    runs-on: windows-latest
    steps:
      - name: 📚 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🏗️ Build Windows
        run: flutter build windows --release

      - name: 🤐 Compress Windows Build
        run: |
          Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath Perfos_Windows.zip

      - name: 📤 Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Perfos-Windows-App
          path: Perfos_Windows.zip

  # 3. COMPILATION AUTOMATIQUE LINUX
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Install Linux Build Dependencies
        run: |
          sudo apt update
          sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🌐 Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: 🏗️ Build Linux
        run: flutter build linux --release

      - name: 🤐 Compress Linux Build
        run: |
          cd build/linux/x64/release/bundle
          zip -r ../../../../Perfos_Linux.zip .

      - name: 📤 Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Perfos-Linux-App
          path: Perfos_Linux.zip
